config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users, path: 'auth'
  resources :users, only: %i[index show destroy] do
    resources :comments, module: 'users'
  end

  namespace :api do
    namespace :v1 do
      resources :books, only: %i[index]
      resources :authors do
        scope module: 'authors' do
          resources :books, only: %i[index]
        end
      end
    end
  end

  resources :books do
    resources :comments, module: 'books'
  end

  resources :likes, only: %i[create destroy]
  resources :follows, only: %i[create destroy]
  resources :notifications, only: %i[create destroy]
  root to: 'users#index'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
  validates :name, :age, presence: true
  validates :avatar, content_type: ['image/png', 'image/jpg', 'image/jpeg']
  validates :age, numericality: { greater_than: 0, less_than: 100 }
  has_many :books, foreign_key: 'author_id'
  has_many :comments, as: :commentable
  has_many :notifications, foreign_key: 'author_id'
  has_many :followers, class_name: 'Follow', foreign_key: 'followee_id', dependent: :delete_all
  has_one_attached :avatar

  def liked_book?(book)
    book.likes.exists?(author: self)
  end

  def followed_by?(user)
    followers.exists?(follower_id: user.id)
  end
end

app/controllers/users/comments_controller.rb
# frozen_string_literal: true

module Users
  class CommentsController < ApplicationController
    before_action :setup_user
    def create
      @comment = @user.comments.new(permitted_params)
      if @comment.save
        flash[:notice] = 'Comment posted!'
      else
        flash[:alert] = 'Error while posting a comment'
      end
      redirect_to user_path(@user)
    end

    def destroy
      @comment = @user.comments.find_by!(id: params[:id], author: current_user)
      if @comment.destroy
        flash[:notice] = 'Comment deleted!'
      else
        flash[:alert] = 'Error while deleting a comment'
      end
      redirect_to user_path(@user)
    end

    private

    def permitted_params
      params.require(:comment)
            .permit(:text)
            .merge(author_id: current_user.id)
    end

    def setup_user
      @user = User.find(params[:user_id])
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < AuthenticationController
  before_action :find_user, only: %i[show destroy]
  def index
    @users = User.where.not(id: current_user)
  end

  def show
    @comment = Comment.new
  end

  private

  def find_user
    @user = User.find(params[:id])
  end
end

app/views/users/index.html.erb
<h1>Authors</h1>
<%= link_to 'Log out', destroy_user_session_path, method: :delete %>
<%= link_to 'Create a book', new_book_path %>
<%= link_to 'Profile', user_path(current_user) %>
<h2>Notifications</h2>
<% if current_user.notifications.any? %>
  <ul>
    <% current_user.notifications.each do |notification| %>
      <li>
        <p>
          <%= notification.title %><br>
          <%= notification.text %>
          <%= link_to 'Delete', notification_path(notification), method: :delete, data: { confirm: 'Are u sure?' } %>
        </p>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>Nothing to show</p>
<% end %>
<hr>
<% @users.each do |user| %>
  <p>Name: <%= user.name %></p>
  <p>Age: <%= user.age %></p>
  <%= link_to 'Show', user_path(user) %>
  <hr>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<% if @user != current_user %>
  <% if @user.followed_by?(current_user) %>
    <%= link_to 'Unfollow', follow_path(@user.followers.find_by(follower: current_user)), method: :delete %>
  <% else %>
    <%= link_to 'Follow', follows_path(follow: { followee_id: @user.id }), method: :post %>
  <% end %>
<% end %>
<% if @user.avatar.attached? %>
  <%= image_tag @user.avatar.representation(resize_to_limit: [100, 100]) %>
<% end %>
<p>Name: <%= @user.name %></p>
<p>Age: <%= @user.age %></p>
<h2>Comments</h2>
<% if @user.comments.any? %>
  <ul>
    <% @user.comments.each do |comment| %>
      <li> <%= comment.text %>
        <% if comment.author == current_user %>
          <%= link_to 'Delete', user_comment_path(@user, comment), method: :delete, data: { confirm: 'Are u sure?' } %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p> No comments posted yet </p>
<% end %>
<%= render 'comments/form', path: user_comments_path(@user), placeholder: 'Write a comment...' %>
<hr>
<% if current_user == @user %>
  <h2>Your books</h2>
<% else %>
  <h2>Books of <%= @user.name  %></h2>
<% end%>
<% if @user.books.any? %>
  <% @user.books.each do |book| %>
    <div>
      <p>Title: <%= book.title %></p>
      <p>Pages: <%= book.number_of_pages %></p>
      <p>Author: <%= book.author.name %></p>
    </div>
    <% if current_user == @user %>
      <%= link_to 'Edit',  edit_book_path(book) %>
      <%= link_to 'Delete',  book_path(book), method: :delete, :data => {:confirm => 'Are you sure?'} %>
    <% end %>
    <%= link_to 'Show', book_path(book) %>
    <% if current_user.liked_book?(book) %>
      <%= link_to 'Unlike', like_path(book.likes.find_by(author: current_user)), method: :delete %>
    <% else %>
      <%= link_to 'Like', likes_path(like: { book_id: book.id }), method: :post %>
    <% end %>
    <hr>
  <% end %>
<% else %>
  <p>Nothing to show</p>
<% end %>
<%= link_to 'Back', users_path %>