config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users, path: 'auth'
  resources :users, only: %i[index show destroy] do
    resources :comments, module: 'users'
  end

  namespace :api do
    namespace :v1 do
      resources :books, only: %i[index]
      resources :authors do
        scope module: 'authors' do
          resources :books, only: %i[index]
        end
      end
    end
  end

  resources :books do
    resources :comments, module: 'books'
  end

  resources :likes, only: %i[create destroy]
  resources :follows, only: %i[create destroy]
  resources :notifications, only: %i[create destroy]
  root to: 'users#index'
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  validates :title, :number_of_pages, :synopsis, presence: true
  validates :cover, content_type: ['image/png', 'image/jpg', 'image/jpeg']
  belongs_to :author, class_name: 'User'

  delegate :name, to: :author, prefix: 'author'
  has_one_attached :cover
  has_rich_text :synopsis
  has_many :comments, as: :commentable
  has_many :likes, dependent: :delete_all
  after_commit :notify_followers, on: :create

  private

  def notify_followers
    SendBookCreatedNotificationToUsersJob.perform_later(author.id, id)
  end
end

app/controllers/api/v1/authors/books_controller.rb
# frozen_string_literal: true

class Api::V1::Authors::BooksController < Api::ApiController
  before_action :setup_author

  def index
    render json: @author.books
  end

  private

  def setup_author
    @author = User.find_by(id: params[:author_id])
    render json: {}, status: :not_found unless @author
  end
end

app/controllers/api/v1/books_controller.rb
# frozen_string_literal: true

class Api::V1::BooksController < Api::ApiController
  def index
    @books = Book.all
    render json: @books
  end
end

app/controllers/books/comments_controller.rb
# frozen_string_literal: true

module Books
  class CommentsController < ApplicationController
    before_action :setup_book

    def create
      @comment = @book.comments.new(permitted_params)
      if @comment.save
        flash[:notice] = 'Comment posted!'
      else
        flash[:alert] = 'Error while posting a comment'
      end
      redirect_to book_path(@book)
    end

    def destroy
      @comment = @book.comments.find_by!(id: params[:id], author: current_user)
      if @comment.destroy
        flash[:notice] = 'Comment deleted!'
      else
        flash[:alert] = 'Error while deleting a comment'
      end
      redirect_to book_path(@book)
    end

    private

    def permitted_params
      params.require(:comment)
            .permit(:text)
            .merge(author_id: current_user.id)
    end

    def setup_book
      @book = Book.find(params[:book_id])
    end
  end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < AuthenticationController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = current_user.books.new(permitted_params)
    if @book.save
      flash[:notice] = 'Book created!'
      redirect_to user_path(current_user)
    else
      flash.now[:alert] = 'Error while creating a book'
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find_by(id: params[:id], author: current_user)
    if @book.update(permitted_params)
      flash[:notice] = 'Book updated!'
      redirect_to user_path(current_user)
    else
      flash.now[:alert] = 'Error while updating the book'
      render :edit
    end
  end

  def show
    @book = Book.find(params[:id])
    @comment = Comment.new
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      flash[:notice] = 'Book deleted!'
    else
      flash[:alert] = 'Error while deleting book'
    end
    redirect_to user_path(current_user)
  end

  private

  def permitted_params
    params.require(:book)
          .permit(:title, :number_of_pages, :author_id, :cover, :synopsis)
  end
end

app/views/books/_form.html.erb
<%= form_with  model: @book, local: true do |f| %>
  <div>
    <%= f.label :title, 'Title' %>:<br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :cover, 'Cover' %><br />
    <%= f.file_field :cover, accept: 'image/*' %>
  </div>

  <div>
    <%= f.label :number_of_pages, 'Pages' %>:<br>
    <%= f.number_field :number_of_pages %>
  </div>

  <div>
    <%= f.label :synopsis, 'Synopsis' %>:<br>
    <%= f.rich_text_area :synopsis %>
  </div>

  <%= f.submit %>
  <%= link_to 'Back', users_path %>
<% end %>

app/views/books/edit.html.erb
<h2>Edit a book</h2>
<hr/>
<br/>
<%= render 'form' %>

app/views/books/index.html.erb
<h1>Books of <%= current_user.name  %></h1>
<hr>
<% @books.each do |book| %>
  <div>
    <p>Title: <%= book.title %></p>
    <p>Pages: <%= book.number_of_pages %></p>
    <p>Author: <%= book.author_name %></p>
  </div>
  <hr>
<% end %>

app/views/books/new.html.erb
<h2>Create a book</h2>
<hr/>
<br/>
<%= render 'form' %>

app/views/books/show.html.erb
<h1> <%= @book.title %> </h1>
<% if @book.cover.attached? %>
  <%= image_tag @book.cover.representation(resize_to_limit: [100, 100]) %>
<% end %>
<p> Pages: <%= @book.number_of_pages %> </p>
<h2>Synopsis</h2>
<p> <%= @book.synopsis %> </p>
<h2>Comments</h2>
<% if @book.comments.any? %>
  <ul>
    <% @book.comments.each do |comment| %>
      <li> <%= comment.text %>
        <% if comment.author == current_user %>
          <%= link_to 'Delete', book_comment_path(@book, comment), method: :delete, data: { confirm: 'Are u sure?' } %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p> No comments posted yet </p>
<% end %>
<%= render 'comments/form', path: book_comments_path(@book), placeholder: 'Write a comment...' %>
<%= link_to 'Back', user_path(@book.author) %>